version: '3'

services:
  quacker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - quacker-net

  mi-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - quacker-net
    volumes:
      - mi-mongo-data:/data/db

networks:
  quacker-net:
    driver: bridge

volumes:
  mi-mongo-data:
    driver: local